;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LilyPond-electric-close-paren
        LilyPond-save-buffer
        TeX-insert-backslash
        end-of-visual-line
        ess-electric-brace
        ess-smart-S-assign
        ess-smart-comma
        ess-yank
        eval-print-last-sexp
        go-mode-insert-and-indent
        indent-for-tab-command
        kill-visual-line
        my-c-w
        org-agenda-deadline
        org-agenda-next-line
        org-agenda-previous-line
        org-agenda-schedule
        org-agenda-todo
        org-archive-subtree-default
        org-beginning-of-line
        org-delete-char
        org-end-of-line
        org-insert-todo-heading
        org-kill-line
        org-meta-return
        org-return-indent
        org-schedule
        org-self-insert-command
        org-shiftmetaright
        org-shiftright
        org-smart-beginning-of-line
        org-todo
        python-fill-paragraph
        python-indent-electric-colon
        python-nav-forward-block
        reindent-then-newline-and-indent
        sgml-slash
        smart-beginning-of-line
        transpose-words
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        beginning-of-buffer
        end-of-buffer
        helm-projectile
        ido-switch-buffer
        pp-eval-last-sexp
        ))
