(deftheme ben-solarized-dark
  "Created 2015-06-21.")

(custom-theme-set-variables
 'ben-solarized-dark
 '(ansi-color-names-vector ["#073642" "#dc322f" "#859900" "#b58900" "#268bd2" "#d33682" "#2aa198" "#657b83"])
 '(compilation-message-face (quote (quote default)))
 '(magit-use-overlays nil))

(let* ((class '((class color) (min-colors 89))))
  (custom-theme-set-faces
   'ben-solarized-dark
   '(shadow ((t (:foreground "#586e75"))))
   '(match ((t (:background "#073642" :foreground "#93a1a1" :weight bold))))
   '(cursor ((t (:foreground "#002b36" :background "#839496" :inverse-video t))))
   '(escape-glyph ((t (:foreground "#6c71c4"))))
   '(fringe ((t (:background "#002b36" :foreground "#586e75"))))
   '(highlight ((t (:background "#073642"))))
   '(link ((t (:foreground "#b58900" :underline t :weight bold))))
   '(link-visited ((t (:foreground "#b58900" :underline t :weight normal))))
   '(success ((t (:foreground "#859900"))))
   '(warning ((t (:foreground "#b58900"))))
   '(error ((t (:foreground "#cb4b16"))))
   '(lazy-highlight ((t (:foreground "#002b36" :background "#b58900" :weight normal))))
   '(widget-field ((t (:background "#073642"))))
   '(button ((t (:underline t))))
   '(compilation-column-number ((t (:inherit font-lock-doc-face :foreground "#2aa198" :underline nil))))
   '(compilation-error ((t (:inherit error :underline nil))))
   '(compilation-info ((t (:foreground "#586e75" :underline nil :bold nil))))
   '(compilation-line-number ((t (:foreground "#859900" :underline nil))))
   '(compilation-warning ((t (:inherit warning :underline nil))))
   '(compilation-mode-line-exit ((t (:foreground unspecified :weight bold))))
   '(compilation-mode-line-fail ((t (:inherit compilation-error :foreground "#dc322f" :weight bold))))
   '(compilation-mode-line-run ((t (:foreground "#cb4b16" :weight bold))))
   '(diary ((t (:foreground "#b58900"))))
   '(dired-directory ((t (:foreground "#268bd2" :weight normal))))
   '(dired-flagged ((t (:foreground "#dc322f"))))
   '(dired-header ((t (:foreground "#002b36" :background "#268bd2"))))
   '(dired-ignored ((t (:inherit shadow))))
   '(dired-mark ((t (:foreground "#b58900" :weight bold))))
   '(dired-marked ((t (:foreground "#d33682" :weight bold))))
   '(dired-perm-write ((t (:foreground "#839496" :underline t))))
   '(dired-symlink ((t (:foreground "#2aa198" :weight normal :slant italic))))
   '(dired-warning ((t (:foreground "#cb4b16" :underline t))))
   '(completions-annotations ((t (:foreground "#586e75"))))
   '(isearch ((t (:foreground "#002b36" :background "#d33682" :weight normal))))
   '(isearch-fail ((t (:foreground "#dc322f" :background "#002b36" :bold t))))
   '(menu ((t (:foreground "#839496" :background "#002b36"))))
   '(minibuffer-prompt ((t (:foreground "#839496"))))
   '(mode-line ((t (:inverse-video unspecified :overline "#073642" :underline "#284b54" :foreground "#839496" :background "#073642" :box (:line-width 1 :color "#073642" :style unspecified)))))
   '(mode-line-buffer-id ((t (:weight bold))))
   '(mode-line-inactive ((t (:inverse-video unspecified :overline "#073642" :underline "#284b54" :foreground "#586e75" :background "#002b36" :box (:line-width 1 :color "#002b36" :style unspecified)))))
   '(header-line ((t (:inverse-video unspecified :overline nil :underline "#073642" :foreground "#839496" :background "#002b36" :box (:line-width 2 :color "#002b36" :style unspecified)))))
   '(region ((t (:foreground "#002b36" :background "#93a1a1"))))
   '(secondary-selection ((t (:background "#073642"))))
   '(trailing-whitespace ((t (:background "#dc322f"))))
   '(vertical-border ((t (:foreground "#284b54"))))
   '(font-lock-builtin-face ((t (:foreground "#839496" :weight bold :slant normal))))
   '(font-lock-comment-delimiter-face ((t (:foreground "#586e75" :slant normal))))
   '(font-lock-comment-face ((t (:foreground "#586e75"))))
   '(font-lock-constant-face ((t (:foreground "#268bd2" :weight bold))))
   '(font-lock-doc-face ((t (:foreground "#2aa198" :slant normal))))
   '(font-lock-function-name-face ((t (:foreground "#268bd2"))))
   '(font-lock-keyword-face ((t (:foreground "#859900" :weight bold))))
   '(font-lock-negation-char-face ((t (:foreground "#b58900" :weight bold))))
   '(font-lock-preprocessor-face ((t (:foreground "#268bd2"))))
   '(font-lock-regexp-grouping-construct ((t (:foreground "#b58900" :weight bold))))
   '(font-lock-regexp-grouping-backslash ((t (:foreground "#859900" :weight bold))))
   '(font-lock-string-face ((t (:foreground "#2aa198"))))
   '(font-lock-type-face ((t (:foreground "#b58900"))))
   '(font-lock-variable-name-face ((t (:foreground "#268bd2"))))
   '(font-lock-warning-face ((t (:inherit error :weight bold))))
   '(ac-candidate-face ((t (:background "#073642" :foreground "#2aa198"))))
   '(ac-selection-face ((t (:background "#00736F" :foreground "#69CABF"))))
   '(ac-candidate-mouse-face ((t (:background "#69CABF" :foreground "#00736F"))))
   '(ac-completion-face ((t (:foreground "#93a1a1" :underline t))))
   '(ctbl:face-cell-select ((t (:background "#073642" :foreground "#93a1a1" :underline "#93a1a1" :weight bold))))
   '(ctbl:face-continue-bar ((t (:background "#073642" :foreground "#b58900"))))
   '(ctbl:face-row-select ((t (:background "#073642" :foreground "#839496" :underline t))))
   '(custom-face-tag ((t (:inherit variable-pitch :height 1.2 :foreground "#6c71c4" :weight normal))))
   '(custom-variable-tag ((t (:inherit variable-pitch :foreground "#2aa198" :height 1.2))))
   '(custom-comment-tag ((t (:foreground "#586e75"))))
   '(custom-group-tag ((t (:inherit variable-pitch :foreground "#268bd2" :height 1.2))))
   '(custom-group-tag-1 ((t (:inherit variable-pitch :foreground "#dc322f" :height 1.2))))
   '(custom-state ((t (:foreground "#859900"))))
   '(custom-button ((t (:background "#073642" :foreground "#93a1a1" :box (:line-width 2 :style released-button)))))
   '(custom-button-mouse ((t (:background "#586e75" :foreground "#073642" :box (:line-width 2 :style released-button)))))
   '(custom-button-pressed ((t (:background "#586e75" :foreground "#93a1a1" :box (:line-width 2 :style pressed-button)))))
   '(custom-button-unraised ((t (:inherit underline))))
   '(custom-button-pressed-unraised ((t (:inherit custom-button-unraised :foreground "#d33682"))))
   '(diff-added ((t (:foreground "#859900" :background nil))))
   '(diff-changed ((t (:foreground "#268bd2" :background nil))))
   '(diff-removed ((t (:foreground "#dc322f" :background nil))))
   '(diff-header ((t (:background "#002b36"))))
   '(diff-file-header ((t (:background "#002b36" :foreground "#839496" :weight bold))))
   '(diff-refine-added ((t (:foreground "#859900" :background "#002b36" :inverse-video t))))
   '(diff-refine-changed ((t (:foreground "#268bd2" :background "#002b36" :inverse-video t))))
   '(diff-refine-removed ((t (:foreground "#dc322f" :background "#002b36" :inverse-video t))))
   '(epa-mark ((t (:foreground "#d33682" :weight bold))))
   '(epa-string ((t (:foreground "#6c71c4"))))
   '(epa-validity-disabled ((t (:inverse-video t :slant italic))))
   '(epa-validity-high ((t (:weight bold))))
   '(epa-validity-low ((t (:slant italic))))
   '(epa-validity-medium ((t (:slant italic))))
   '(epc:face-title ((t (:foreground "#268bd2" :background "#002b36" :weight normal :underline nil))))
   '(helm-bookmark-directory ((t (:inherit helm-ff-directory))))
   '(helm-bookmark-file ((t (:foreground "#839496"))))
   '(helm-bookmark-gnus ((t (:foreground "#2aa198"))))
   '(helm-bookmark-info ((t (:foreground "#859900"))))
   '(helm-bookmark-man ((t (:foreground "#6c71c4"))))
   '(helm-bookmark-w3m ((t (:foreground "#b58900"))))
   '(helm-buffer-not-saved ((t (:foreground "#cb4b16"))))
   '(helm-buffer-saved-out ((t (:foreground "#dc322f" :background "#002b36" :inverse-video t))))
   '(helm-buffer-size ((t (:foreground "#586e75"))))
   '(helm-candidate-number ((t (:background "#073642" :foreground "#93a1a1" :bold t))))
   '(helm-ff-directory ((t (:background "#002b36" :foreground "#268bd2"))))
   '(helm-ff-executable ((t (:foreground "#859900"))))
   '(helm-ff-file ((t (:background "#002b36" :foreground "#839496"))))
   '(helm-ff-invalid-symlink ((t (:background "#002b36" :foreground "#cb4b16" :slant italic))))
   '(helm-ff-prefix ((t (:background "#b58900" :foreground "#002b36"))))
   '(helm-ff-symlink ((t (:foreground "#2aa198"))))
   '(helm-grep-file ((t (:foreground "#2aa198" :underline t))))
   '(helm-grep-finish ((t (:foreground "#859900"))))
   '(helm-grep-lineno ((t (:foreground "#cb4b16"))))
   '(helm-grep-match ((t (:inherit match))))
   '(helm-grep-running ((t (:foreground "#dc322f"))))
   '(helm-header ((t (:inherit header-line))))
   '(helm-lisp-completion-info ((t (:foreground "#839496"))))
   '(helm-lisp-show-completion ((t (:foreground "#b58900" :background "#073642" :bold t))))
   '(helm-M-x-key ((t (:foreground "#cb4b16" :underline t))))
   '(helm-moccur-buffer ((t (:foreground "#2aa198" :underline t))))
   '(helm-match ((t (:inherit match))))
   '(helm-selection ((t (:background "#073642" :underline t))))
   '(helm-selection-line ((t (:background "#073642" :foreground "#93a1a1" :underline nil))))
   '(helm-separator ((t (:foreground "#dc322f"))))
   '(helm-source-header ((t (:background "#00629D" :foreground "#002b36" :underline nil))))
   '(helm-visible-mark ((t (:background "#002b36" :foreground "#d33682" :bold t))))
   '(ido-first-match ((t (:foreground "#b58900" :weight normal))))
   '(ido-only-match ((t (:foreground "#002b36" :background "#b58900" :weight normal))))
   '(ido-subdir ((t (:foreground "#268bd2"))))
   '(ido-incomplete-regexp ((t (:foreground "#dc322f" :weight bold))))
   '(ido-indicator ((t (:background "#dc322f" :foreground "#002b36" :width condensed))))
   '(ido-virtual ((t (:foreground "#2aa198"))))
   '(info-title-1 ((t (:foreground "#93a1a1" :weight bold))))
   '(info-title-2 ((t (:foreground "#93a1a1" :weight bold))))
   '(info-title-3 ((t (:weight bold))))
   '(info-title-4 ((t (:weight bold))))
   '(info-node ((t (:foreground "#93a1a1" :slant italic :weight bold))))
   '(info-header-node ((t (:inherit info-node))))
   '(info-header-xref ((t (:inherit info-xref))))
   '(info-index-match ((t (:inherit match))))
   '(info-menu-header ((t (:inherit variable-pitch :weight bold))))
   '(info-menu-star ((t (:foreground "#cb4b16"))))
   '(info-xref ((t (:inherit link))))
   '(info-xref-visited ((t (:inherit (link-visited info-xref)))))
   '(jedi:highlight-function-argument ((t (:inherit bold))))
   '(linum ((t (:foreground "#586e75" :background "#002b36"))))
   '(magit-section-title ((t (:foreground "#b58900" :weight bold))))
   '(magit-branch ((t (:foreground "#cb4b16" :weight bold))))
   '(magit-item-highlight ((t (:background "#073642" :weight unspecified))))
   '(magit-log-author ((t (:foreground "#2aa198"))))
   '(magit-log-graph ((t (:foreground "#586e75"))))
   '(magit-log-head-label-bisect-bad ((t (:background "#FF6E64" :foreground "#990A1B" :box 1))))
   '(magit-log-head-label-bisect-good ((t (:background "#B4C342" :foreground "#546E00" :box 1))))
   '(magit-log-head-label-default ((t (:background "#073642" :box 1))))
   '(magit-log-head-label-local ((t (:background "#00629D" :foreground "#69B7F0" :box 1))))
   '(magit-log-head-label-patches ((t (:background "#990A1B" :foreground "#FF6E64" :box 1))))
   '(magit-log-head-label-remote ((t (:background "#546E00" :foreground "#B4C342" :box 1))))
   '(magit-log-head-label-tags ((t (:background "#7B6000" :foreground "#DEB542" :box 1))))
   '(magit-log-sha1 ((t (:foreground "#b58900"))))
   '(magit-cherry-equivalent ((t (:foreground "#d33682"))))
   '(magit-cherry-unmatched ((t (:foreground "#2aa198"))))
   '(magit-process-ng ((t (:inherit magit-header :foreground "#dc322f"))))
   '(magit-process-ok ((t (:inherit magit-header :foreground "#859900"))))
   '(magit-signature-bad ((t (:foreground "#dc322f"))))
   '(magit-signature-good ((t (:foreground "#859900"))))
   '(magit-signature-none ((t (:inherit magit-log-message))))
   '(magit-signature-untrusted ((t (:foreground "#2aa198"))))
   '(magit-whitespace-warning-face ((t (:inherit trailing-whitespace))))
   '(mc/cursor-face ((t (:inherit cursor :inverse-video nil))))
   '(message-cited-text ((t (:foreground "#586e75"))))
   '(message-header-name ((t (:foreground "#586e75"))))
   '(message-header-other ((t (:foreground "#839496" :weight normal))))
   '(message-header-to ((t (:foreground "#839496" :weight normal))))
   '(message-header-cc ((t (:foreground "#839496" :weight normal))))
   '(message-header-newsgroups ((t (:foreground "#b58900" :weight bold))))
   '(message-header-subject ((t (:foreground "#2aa198" :weight normal))))
   '(message-header-xheader ((t (:foreground "#2aa198"))))
   '(message-mml ((t (:foreground "#b58900" :weight bold))))
   '(message-separator ((t (:foreground "#586e75" :slant italic))))
   '(popup-face ((t (:background "#073642" :foreground "#839496"))))
   '(popup-isearch-match ((t (:background "#b58900" :foreground "#002b36"))))
   '(popup-menu-face ((t (:background "#073642" :foreground "#839496"))))
   '(popup-menu-mouse-face ((t (:background "#268bd2" :foreground "#002b36"))))
   '(popup-menu-selection-face ((t (:background "#d33682" :foreground "#002b36"))))
   '(popup-scroll-bar-background-face ((t (:background "#586e75"))))
   '(popup-scroll-bar-foreground-face ((t (:background "#93a1a1"))))
   '(popup-tip-face ((t (:background "#073642" :foreground "#839496"))))
   '(powerline-active1 ((t (:background "#002b36" :foreground "#657b83"))))
   '(powerline-active2 ((t (:background "#073642" :foreground "#657b83"))))
   '(powerline-inactive1 ((t (:background "#073642" :foreground "#586e75"))))
   '(powerline-inactive2 ((t (:background "#002b36" :foreground "#586e75"))))
   '(show-paren-match ((t (:foreground "#d33682" :background unspecified :weight bold))))
   '(show-paren-mismatch ((t (:foreground "#073642" :background "#dc322f" :weight bold))))
   '(tooltip ((t (:background "#7B6000" :foreground "#DEB542" :inherit variable-pitch))))
   '(undo-tree-visualizer-default-face ((t (:foreground "#586e75" :background "#002b36"))))
   '(undo-tree-visualizer-unmodified-face ((t (:foreground "#859900"))))
   '(undo-tree-visualizer-current-face ((t (:foreground "#268bd2" :inverse-video t))))
   '(undo-tree-visualizer-active-branch-face ((t (:foreground "#93a1a1" :background "#002b36" :weight bold))))
   '(undo-tree-visualizer-register-face ((t (:foreground "#b58900"))))
   '(which-func ((t (:foreground "#859900"))))
   '(yas-field-highlight-face ((t (:inherit secondary-selection))))
   '(default ((t (:background "#002b36" :foreground "#839496" :height 110 :family "Consolas"))))))

(provide-theme 'ben-solarized-dark)
